Towns Life: ST::Game Class Reference
ST::Game Class Reference
#include <game.h>
Public Member Functions
Game (const std::string &path)
~Game ()
void run ()
void changeState (GameState *state)
void disconnect ()
bool connect (const std::string &server, int port)
Private Member Functions
void cleanUp ()
Private Attributes
GameState * mState
GameState * mOldState
Detailed Description
The Game class controls the graphics, input, sound and networking It loops until the user exits
Definition at line 64 of file game.h.
Constructor & Destructor Documentation
ST::Game::Game (const std::string & path)
Definition at line 71 of file game.cpp.
References ST::logger, and ST::resourceManager.
ST::Game::~Game ()
Destructor
Cleans up Game
Definition at line 77 of file game.cpp.
References ST::beingManager, ST::graphicsEngine, ST::inputManager, ST::interfaceManager, ST::logger, ST::mapEngine, ST::networkManager, ST::player, and ST::resourceManager.
Member Function Documentation
void ST::Game::run ()
Run
Creates everything needed to run the game Loops until user exists the game
Definition at line 90 of file game.cpp.
References ST::beingManager, cleanUp(), ST::GameState::enter(), ST::InputManager::getEvents(), ST::graphicsEngine, ST::inputManager, ST::interfaceManager, ST::logger, ST::mapEngine, mOldState, mState, ST::networkManager, ST::player, and ST::GameState::update().
Referenced by main().
void ST::Game::changeState (GameState * state)
Change State
Changes which state the client is in
Parameters:
state The gamestate to change to
Definition at line 144 of file game.cpp.
References ST::GameState::enter(), ST::GameState::exit(), mOldState, and mState.
Referenced by ST::RegisterState::update().
void ST::Game::disconnect ()
Disconnects from a server
This actually just sends a disconnect packet since its using connection-less UDP packets
Definition at line 161 of file game.cpp.
References ST::InputManager::getEvents(), ST::graphicsEngine, ST::inputManager, mState, ST::networkManager, and ST::GameState::update().
Referenced by ST::TestState::update().
bool ST::Game::connect (const std::string & server, int port)
Connect to a server
This actually just sends a message, as its using connection-less UDP packets
Parameters:
server The hostname of the server
port The port of the server
Definition at line 173 of file game.cpp.
References ST::InputManager::getEvents(), ST::graphicsEngine, ST::inputManager, mState, ST::networkManager, ST::timeout, and ST::GameState::update().
void ST::Game::cleanUp () [private]
Definition at line 152 of file game.cpp.
References mOldState, and ST::GameState::noKeep().
Referenced by run().
Member Data Documentation
GameState* ST::Game::mState [private]
Definition at line 114 of file game.h.
Referenced by changeState(), connect(), disconnect(), and run().
GameState* ST::Game::mOldState [private]
Definition at line 115 of file game.h.
Referenced by changeState(), cleanUp(), and run().
The documentation for this class was generated from the following files:
programming/smalltowns/src/game.h
programming/smalltowns/src/game.cpp