Towns Life: ST::ResourceManager Class Reference
ST::ResourceManager Class Reference
#include <resourcemanager.h>
Public Member Functions
ResourceManager (const std::string &path)
~ResourceManager ()
void loadBodyParts (const std::string &filename)
void loadAnimations (const std::string &filename)
int getBodyWidth () const
int getBodyHeight () const
BodyPart * getBodyPart (int id)
BodyPart * getDefaultBody (int type)
BodyPart * getFemaleBody ()
std::vector< BodyPart * > getBodyList (int type)
Animation * getAnimation (int bodypart, const std::string &name)
std::string getDataPath ()
bool doesExist (const std::string &filename)
Private Types
typedef std::vector< BodyPart * >
::iterator BodyPartItr
typedef std::map< std::string,
std::list< BeingAnimation * >
>::iterator AnimationItr
Private Attributes
int mBodyWidth
int mBodyHeight
int mDefaultBody
int mDefaultFemale
int mDefaultHair
std::vector< BodyPart * > mBodyParts
std::map< std::string,
std::list< BeingAnimation * > > mAnimations
std::string mDataPath
Detailed Description
The Resource Manager is the class used for storing resources
Definition at line 57 of file resourcemanager.h.
Member Typedef Documentation
typedef std::vector<BodyPart*>::iterator ST::ResourceManager::BodyPartItr [private]
Definition at line 121 of file resourcemanager.h.
typedef std::map<std::string, std::list<BeingAnimation*> >::iterator ST::ResourceManager::AnimationItr [private]
Definition at line 123 of file resourcemanager.h.
Constructor & Destructor Documentation
ST::ResourceManager::ResourceManager (const std::string & path)
Definition at line 54 of file resourcemanager.cpp.
References mBodyHeight, mBodyWidth, mDataPath, mDefaultBody, and mDefaultHair.
ST::ResourceManager::~ResourceManager ()
Definition at line 71 of file resourcemanager.cpp.
References mAnimations, and mBodyParts.
Member Function Documentation
void ST::ResourceManager::loadBodyParts (const std::string & filename)
Loads the body parts from file
Definition at line 104 of file resourcemanager.cpp.
References mBodyHeight, mBodyParts, mBodyWidth, mDataPath, mDefaultBody, mDefaultFemale, and mDefaultHair.
Referenced by ST::CharacterState::CharacterState().
void ST::ResourceManager::loadAnimations (const std::string & filename)
Loads the animations from file
Definition at line 136 of file resourcemanager.cpp.
References ST::graphicsEngine, mAnimations, and mDataPath.
Referenced by ST::CharacterState::CharacterState().
int ST::ResourceManager::getBodyWidth () const
Returns width of body parts
Definition at line 182 of file resourcemanager.cpp.
References mBodyWidth.
int ST::ResourceManager::getBodyHeight () const
Returns height of body parts
Definition at line 187 of file resourcemanager.cpp.
References mBodyHeight.
BodyPart * ST::ResourceManager::getBodyPart (int id)
Returns Body part based on id
Parameters:
id The id of the body part
Definition at line 192 of file resourcemanager.cpp.
References mBodyParts.
Referenced by getDefaultBody(), and getFemaleBody().
BodyPart * ST::ResourceManager::getDefaultBody (int type)
Returns the default body part based on type
Parameters:
type The type of body part
Definition at line 208 of file resourcemanager.cpp.
References getBodyPart(), mDefaultBody, and mDefaultHair.
Referenced by ST::change_sex(), ST::CharacterState::CharacterState(), and ST::CharacterState::createAvatar().
BodyPart * ST::ResourceManager::getFemaleBody ()
Definition at line 221 of file resourcemanager.cpp.
References getBodyPart(), and mDefaultFemale.
Referenced by ST::change_sex().
std::vector< BodyPart * > ST::ResourceManager::getBodyList (int type)
Returns a list of all body parts of a certain type
Parameters:
type The type of body part
Definition at line 226 of file resourcemanager.cpp.
References mBodyParts.
Referenced by ST::CharacterState::createCreationWindow().
Animation * ST::ResourceManager::getAnimation (int bodypart, const std::string & name)
Returns Animation based on body part id and animation name
Parameters:
bodypart Id of body part
name Name of animation
Definition at line 244 of file resourcemanager.cpp.
References mAnimations.
Referenced by ST::Being::setAnimation().
std::string ST::ResourceManager::getDataPath ()
Returns the path to data directory
Definition at line 264 of file resourcemanager.cpp.
References mDataPath.
Referenced by ST::Map::loadMap(), and ST::Map::loadTileset().
bool ST::ResourceManager::doesExist (const std::string & filename)
Check a file or path exists
Definition at line 269 of file resourcemanager.cpp.
Referenced by ST::Map::loadTileset().
Member Data Documentation
int ST::ResourceManager::mBodyWidth [private]
Definition at line 115 of file resourcemanager.h.
Referenced by getBodyWidth(), loadBodyParts(), and ResourceManager().
int ST::ResourceManager::mBodyHeight [private]
Definition at line 116 of file resourcemanager.h.
Referenced by getBodyHeight(), loadBodyParts(), and ResourceManager().
int ST::ResourceManager::mDefaultBody [private]
Definition at line 117 of file resourcemanager.h.
Referenced by getDefaultBody(), loadBodyParts(), and ResourceManager().
int ST::ResourceManager::mDefaultFemale [private]
Definition at line 118 of file resourcemanager.h.
Referenced by getFemaleBody(), and loadBodyParts().
int ST::ResourceManager::mDefaultHair [private]
Definition at line 119 of file resourcemanager.h.
Referenced by getDefaultBody(), loadBodyParts(), and ResourceManager().
std::vector<BodyPart*> ST::ResourceManager::mBodyParts [private]
Definition at line 120 of file resourcemanager.h.
Referenced by getBodyList(), getBodyPart(), loadBodyParts(), and ~ResourceManager().
std::map<std::string, std::list<BeingAnimation*> > ST::ResourceManager::mAnimations [private]
Definition at line 122 of file resourcemanager.h.
Referenced by getAnimation(), loadAnimations(), and ~ResourceManager().
std::string ST::ResourceManager::mDataPath [private]
Definition at line 125 of file resourcemanager.h.
Referenced by getDataPath(), loadAnimations(), loadBodyParts(), and ResourceManager().
The documentation for this class was generated from the following files:
programming/smalltowns/src/resourcemanager.h
programming/smalltowns/src/resourcemanager.cpp