Towns Life: ST::InputManager Class Reference
ST::InputManager Class Reference
#include <input.h>
Public Member Functions
void getEvents ()
bool getKey (SDLKey key)
Private Attributes
std::list< SDLKey > keysDown
Detailed Description
Definition at line 52 of file input.h.
Member Function Documentation
void ST::InputManager::getEvents ()
Get Events Poll for SDL events
Definition at line 50 of file input.cpp.
References ST::interfaceManager, and keysDown.
Referenced by ST::Game::connect(), ST::Game::disconnect(), and ST::Game::run().
bool ST::InputManager::getKey (SDLKey key)
Get Key Check whether a key was pressed
Parameters:
key The key to check was pressed
Returns:
Returns true if key was pressed
Definition at line 84 of file input.cpp.
References keysDown.
Referenced by ST::UpdateState::update(), ST::TestState::update(), ST::RegisterState::update(), ST::LoginState::update(), ST::ConnectState::update(), and ST::CharacterState::update().
Member Data Documentation
std::list<SDLKey> ST::InputManager::keysDown [private]
Definition at line 70 of file input.h.
Referenced by getEvents(), and getKey().
The documentation for this class was generated from the following files:
programming/smalltowns/src/input.h
programming/smalltowns/src/input.cpp