Towns Life: ST::LoginState Class Reference
ST::LoginState Class Reference
#include <loginstate.h>
Public Member Functions
LoginState ()
void enter ()
void exit ()
bool update ()
Private Member Functions
void createLoginWidgets ()
void createRegisterWidgets ()
Private Attributes
XMLFile * file
int mHalfScreenWidth
int mHalfScreenHeight
AG_Window * mLoginWindow
AG_Window * mRegisterWindow
Detailed Description
Definition at line 55 of file loginstate.h.
Constructor & Destructor Documentation
ST::LoginState::LoginState ()
Definition at line 148 of file loginstate.cpp.
References file.
Member Function Documentation
void ST::LoginState::enter () [virtual]
Enter Called when entering the state
Implements ST::GameState.
Definition at line 153 of file loginstate.cpp.
References createLoginWidgets(), createRegisterWidgets(), file, ST::graphicsEngine, ST::interfaceManager, mHalfScreenHeight, mHalfScreenWidth, mLoginWindow, and mRegisterWindow.
void ST::LoginState::exit () [virtual]
Exit Called when leaving the state
Implements ST::GameState.
Definition at line 176 of file loginstate.cpp.
References file, and ST::interfaceManager.
bool ST::LoginState::update () [virtual]
Update Called every frame Return false to exit the game
Implements ST::GameState.
Definition at line 182 of file loginstate.cpp.
References ST::InputManager::getKey(), ST::inputManager, and ST::networkManager.
void ST::LoginState::createLoginWidgets () [private]
Definition at line 197 of file loginstate.cpp.
References file, ST::interfaceManager, mHalfScreenHeight, mHalfScreenWidth, mLoginWindow, mRegisterWindow, ST::submit_login(), and ST::switch_login_window().
Referenced by enter().
void ST::LoginState::createRegisterWidgets () [private]
Definition at line 239 of file loginstate.cpp.
References ST::interfaceManager, mHalfScreenHeight, mHalfScreenWidth, mLoginWindow, mRegisterWindow, ST::submit_register(), and ST::switch_login_window().
Referenced by enter().
Member Data Documentation
XMLFile* ST::LoginState::file [private]
Definition at line 84 of file loginstate.h.
Referenced by createLoginWidgets(), enter(), exit(), and LoginState().
int ST::LoginState::mHalfScreenWidth [private]
Definition at line 85 of file loginstate.h.
Referenced by createLoginWidgets(), createRegisterWidgets(), and enter().
int ST::LoginState::mHalfScreenHeight [private]
Definition at line 86 of file loginstate.h.
Referenced by createLoginWidgets(), createRegisterWidgets(), and enter().
AG_Window* ST::LoginState::mLoginWindow [private]
Definition at line 87 of file loginstate.h.
Referenced by createLoginWidgets(), createRegisterWidgets(), and enter().
AG_Window* ST::LoginState::mRegisterWindow [private]
Definition at line 88 of file loginstate.h.
Referenced by createLoginWidgets(), createRegisterWidgets(), and enter().
The documentation for this class was generated from the following files:
programming/smalltowns/src/loginstate.h
programming/smalltowns/src/loginstate.cpp