Towns Life: ST::TestState Class Reference
ST::TestState Class Reference
#include <teststate.h>
Public Member Functions
TestState ()
void enter ()
void exit ()
bool update ()
Private Attributes
IRCServer * chatServer
Camera * mCam
int ms
int lastframe
Detailed Description
Definition at line 57 of file teststate.h.
Constructor & Destructor Documentation
ST::TestState::TestState ()
Definition at line 126 of file teststate.cpp.
References chatServer, ST::graphicsEngine, mCam, and ms.
Member Function Documentation
void ST::TestState::enter () [virtual]
Enter Called when entering the state
Implements ST::GameState.
Definition at line 141 of file teststate.cpp.
References chatServer, ST::Being::getName(), ST::Player::getSelectedCharacter(), ST::graphicsEngine, ST::handle_mouse(), ST::interfaceManager, ST::player, and ST::submit_chat().
void ST::TestState::exit () [virtual]
Exit Called when leaving the state
Implements ST::GameState.
Definition at line 179 of file teststate.cpp.
References chatServer, ST::interfaceManager, and mCam.
bool ST::TestState::update () [virtual]
Update Called every frame Return false to exit the game
Implements ST::GameState.
Definition at line 187 of file teststate.cpp.
References ST::beingManager, chatServer, ST::Game::disconnect(), game, ST::InputManager::getKey(), ST::Player::getSelectedCharacter(), ST::inputManager, lastframe, ST::Being::logic(), ST::BeingManager::logic(), ms, ST::networkManager, ST::player, and ST::Being::setAnimation().
Member Data Documentation
IRCServer* ST::TestState::chatServer [private]
Definition at line 81 of file teststate.h.
Referenced by enter(), exit(), TestState(), and update().
Camera* ST::TestState::mCam [private]
Definition at line 82 of file teststate.h.
Referenced by exit(), and TestState().
int ST::TestState::ms [private]
Definition at line 83 of file teststate.h.
Referenced by TestState(), and update().
int ST::TestState::lastframe [private]
Definition at line 84 of file teststate.h.
Referenced by update().
The documentation for this class was generated from the following files:
programming/smalltowns/src/teststate.h
programming/smalltowns/src/teststate.cpp