Towns Life: ST::Layer Class Reference
ST::Layer Class Reference
#include <map.h>
Public Member Functions
Layer (unsigned int, unsigned int)
~Layer ()
void setTile (int x, int y, Texture *tex, int width, int height)
void addNode (Node *node)
Node * getNodeAt (unsigned int x, unsigned int y)
Private Types
typedef std::list< Node * >
::iterator NodeItr
Private Attributes
std::list< Node * > mNodes
unsigned int mWidth
unsigned int mHeight
Detailed Description
The Layer class holds map layer data
Definition at line 70 of file map.h.
Member Typedef Documentation
typedef std::list<Node*>::iterator ST::Layer::NodeItr [private]
Definition at line 99 of file map.h.
Constructor & Destructor Documentation
ST::Layer::Layer (unsigned int width, unsigned int height)
Definition at line 58 of file map.cpp.
ST::Layer::~Layer ()
Definition at line 65 of file map.cpp.
References mNodes.
Member Function Documentation
void ST::Layer::setTile (int x, int y, Texture * tex, int width, int height)
Set a tile
Definition at line 76 of file map.cpp.
References addNode(), and ST::graphicsEngine.
Referenced by ST::Map::addLayer().
void ST::Layer::addNode (Node * node)
Add Tile Adds a tile to the layer
Parameters:
tile The tile to add
Definition at line 90 of file map.cpp.
References mNodes.
Referenced by setTile().
Node * ST::Layer::getNodeAt (unsigned int x, unsigned int y)
Get Tile At Returns the tile at x, y
Parameters:
x The x position of the tile to return
y The y position of the tile to return
Returns:
Returns the Tile found at the given location
Definition at line 95 of file map.cpp.
References mNodes.
Member Data Documentation
std::list<Node*> ST::Layer::mNodes [private]
Definition at line 98 of file map.h.
Referenced by addNode(), getNodeAt(), and ~Layer().
unsigned int ST::Layer::mWidth [private]
Definition at line 100 of file map.h.
unsigned int ST::Layer::mHeight [private]
Definition at line 101 of file map.h.
The documentation for this class was generated from the following files:
programming/smalltowns/src/map.h
programming/smalltowns/src/map.cpp