Towns Life: ST::GameState Class Reference
ST::GameState Class Reference
#include <gamestate.h>
Inherited by ST::CharacterState, ST::ConnectState, ST::LoadState, ST::LoginState, ST::OptionsState, ST::TestState, and ST::UpdateState.
Public Member Functions
GameState ()
virtual ~GameState ()
virtual void enter ()=0
virtual void exit ()=0
virtual bool update ()=0
void keep ()
virtual bool noKeep ()
Protected Attributes
bool mKeep
Detailed Description
Definition at line 51 of file gamestate.h.
Constructor & Destructor Documentation
ST::GameState::GameState () [inline]
Definition at line 54 of file gamestate.h.
virtual ST::GameState::~GameState () [inline, virtual]
Definition at line 55 of file gamestate.h.
Member Function Documentation
virtual void ST::GameState::enter () [pure virtual]
Implemented in ST::CharacterState, ST::ConnectState, ST::LoadState, ST::LoginState, ST::OptionsState, ST::TestState, and ST::UpdateState.
Referenced by ST::Game::cleanUp().
virtual void ST::GameState::exit () [pure virtual]
Implemented in ST::CharacterState, ST::ConnectState, ST::LoadState, ST::LoginState, ST::OptionsState, ST::TestState, and ST::UpdateState.
Referenced by ST::Game::cleanUp().
void ST::GameState::keep () [inline]
Definition at line 61 of file gamestate.h.
References mKeep.
virtual bool ST::GameState::noKeep () [inline, virtual]
Definition at line 62 of file gamestate.h.
References mKeep.
Referenced by ST::Game::disconnect().
virtual bool ST::GameState::update () [pure virtual]
Implemented in ST::CharacterState, ST::ConnectState, ST::LoadState, ST::LoginState, ST::OptionsState, ST::TestState, and ST::UpdateState.
Member Data Documentation
bool ST::GameState::mKeep [protected]
Definition at line 65 of file gamestate.h.
Referenced by keep(), and noKeep().
The documentation for this class was generated from the following file:
programming/smalltowns/src/gamestate.h