Towns Life: ST::Being Class Reference
ST::Being Class Reference
#include <being.h>
Inherited by ST::Character.
Public Member Functions
Being (int id, const std::string &name, Texture *avatar)
virtual ~Being ()
virtual std::string getName ()
virtual int getId () const
virtual void setState (int state)
virtual int getState ()
virtual void setAnimation (const std::string &name)
virtual void logic (int ms)
virtual bool calculateNextDestination (const Point &finish)
virtual bool calculateNextDestination ()
virtual void saveDestination (const Point &pos)
virtual void changeAnimation ()
Public Attributes
Look look
Protected Member Functions
void move (int ms)
Point getNextTile (const Point &pt, int dir)
Protected Attributes
int mId
int mState
Pointf mLastPosition
std::deque< Point > mWaypoints
Point mDestination
Detailed Description
Definition at line 77 of file being.h.
Constructor & Destructor Documentation
ST::Being::Being (int id, const std::string & name, Texture * avatar)
Definition at line 84 of file being.cpp.
ST::Being::~Being () [virtual]
Definition at line 107 of file being.cpp.
Member Function Documentation
bool ST::Being::calculateNextDestination () [virtual]
Calculates path finding to get to preset final destination
Returns:
Returns whether it can find a path
Definition at line 234 of file being.cpp.
Referenced by move().
bool ST::Being::calculateNextDestination (const Point & finish) [virtual]
Calculates path finding to get to final destination
Parameters:
finish The destination
Returns:
Returns whether it can find a path
Definition at line 185 of file being.cpp.
void ST::Being::changeAnimation () [virtual]
Change the animation
Definition at line 349 of file being.cpp.
References mDestination.
int ST::Being::getId () const [virtual]
Definition at line 116 of file being.cpp.
std::string ST::Being::getName () [virtual]
Definition at line 111 of file being.cpp.
Referenced by ST::submit_chat().
Point ST::Being::getNextTile (const Point & pt, int dir) [protected]
Definition at line 317 of file being.cpp.
int ST::Being::getState () [virtual]
Returns the animation state of the being
Definition at line 141 of file being.cpp.
References mState.
Referenced by ST::Player::logic().
void ST::Being::logic (int ms) [virtual]
Logic called each frame
Parameters:
ms Number of milliseconds since last frame
Definition at line 121 of file being.cpp.
References mId.
void ST::Being::move (int ms) [protected]
Definition at line 239 of file being.cpp.
References calculateNextDestination(), and mDestination.
void ST::Being::saveDestination (const Point & pos) [virtual]
Stores a destination for path finding
Definition at line 344 of file being.cpp.
void ST::Being::setAnimation (const std::string & name) [virtual]
Set the animation
Definition at line 146 of file being.cpp.
References mState.
void ST::Being::setState (int state) [virtual]
Set the animation state of the being
Definition at line 136 of file being.cpp.
Member Data Documentation
Look ST::Being::look
Definition at line 125 of file being.h.
Point ST::Being::mDestination [protected]
Definition at line 137 of file being.h.
Referenced by changeAnimation(), and move().
int ST::Being::mId [protected]
Definition at line 133 of file being.h.
Referenced by logic().
Pointf ST::Being::mLastPosition [protected]
Definition at line 135 of file being.h.
int ST::Being::mState [protected]
Definition at line 134 of file being.h.
Referenced by getState(), and setAnimation().
std::deque<Point> ST::Being::mWaypoints [protected]
Definition at line 136 of file being.h.
The documentation for this class was generated from the following files:
programming/smalltowns/src/being.h
programming/smalltowns/src/being.cpp