Towns Life: ST::Player Class Reference
ST::Player Class Reference
#include <player.h>
Public Member Functions
Player ()
~Player ()
std::string getName () const
void setName (const std::string &name)
int getId () const
void setId (int id)
void addCharacter (Character *c, int slot)
int getNumChars () const
Character * getCharacter (unsigned int slot)
Character * getSelectedCharacter ()
void removeCharacters ()
void setCharacter (int slot)
Private Types
typedef std::map< int,
Character * > CharacterMap
Private Attributes
std::string mUsername
std::map< int, Character * > mCharacters
Character * mSelected
int mId
Detailed Description
The Player class is for storing player specific variables
Definition at line 53 of file player.h.
Member Typedef Documentation
typedef std::map<int, Character*> ST::Player::CharacterMap [private]
Definition at line 119 of file player.h.
Constructor & Destructor Documentation
ST::Player::Player ()
Constructor
Definition at line 45 of file player.cpp.
References mSelected.
ST::Player::~Player ()
Definition at line 50 of file player.cpp.
References removeCharacters().
Member Function Documentation
std::string ST::Player::getName () const
Returns name
Definition at line 55 of file player.cpp.
References mUsername.
void ST::Player::setName (const std::string & name)
Sets the player's name
Definition at line 60 of file player.cpp.
References mUsername.
Referenced by ST::submit_login(), and ST::submit_register().
int ST::Player::getId () const
Gets the player's id
Definition at line 65 of file player.cpp.
References mId.
void ST::Player::setId (int id)
Sets the player's id
Definition at line 70 of file player.cpp.
References mId.
void ST::Player::addCharacter (Character * c, int slot)
Adds a character for a slot
Parameters:
c The character to add
slot The slot the character is in
Definition at line 75 of file player.cpp.
References mCharacters.
int ST::Player::getNumChars () const
Returns number of characters the player has
Definition at line 85 of file player.cpp.
References mCharacters.
Referenced by ST::CharacterState::createSelectionWindow().
Character * ST::Player::getCharacter (unsigned int slot)
Returns the character in the specified slot
Definition at line 90 of file player.cpp.
References mCharacters.
Referenced by ST::CharacterState::createSelectionWindow().
Character* ST::Player::getSelectedCharacter () [inline]
Returns the selected character
Definition at line 101 of file player.h.
References mSelected.
Referenced by ST::TestState::enter(), ST::submit_chat(), and ST::TestState::update().
void ST::Player::removeCharacters ()
Removes all the currently added characters
Definition at line 101 of file player.cpp.
References mCharacters.
Referenced by ~Player().
void ST::Player::setCharacter (int slot)
Set which character player will use to play
Parameters:
slot The slot of the character selected
Definition at line 113 of file player.cpp.
References mCharacters, and mSelected.
Referenced by ST::select_character().
Member Data Documentation
std::string ST::Player::mUsername [private]
Definition at line 115 of file player.h.
Referenced by getName(), and setName().
std::map<int, Character*> ST::Player::mCharacters [private]
Definition at line 116 of file player.h.
Referenced by addCharacter(), getCharacter(), getNumChars(), removeCharacters(), and setCharacter().
Character* ST::Player::mSelected [private]
Definition at line 117 of file player.h.
Referenced by getSelectedCharacter(), Player(), and setCharacter().
int ST::Player::mId [private]
Definition at line 118 of file player.h.
Referenced by getId(), and setId().
The documentation for this class was generated from the following files:
programming/smalltowns/src/player.h
programming/smalltowns/src/player.cpp