Towns Life: ST::CharacterState Class Reference
ST::CharacterState Class Reference
#include <characterstate.h>
Public Member Functions
CharacterState ()
void enter ()
void exit ()
bool update ()
void updateAvatar (BodyPart *body)
Public Attributes
AG_Checkbox * mSelected
std::vector< int > mChosen
Private Member Functions
void createSelectionWindow ()
void createCreationWindow ()
void createAvatar ()
Private Attributes
int mHalfScreenWidth
int mHalfScreenHeight
AG_Window * mSelectWindow
AG_Window * mCreateWindow
Avatar * mAvatar
Detailed Description
Definition at line 65 of file characterstate.h.
Constructor & Destructor Documentation
ST::CharacterState::CharacterState ()
Definition at line 194 of file characterstate.cpp.
References ST::ResourceManager::getDefaultBody(), ST::ResourceManager::loadAnimations(), ST::ResourceManager::loadBodyParts(), mAvatar, mChosen, mSelected, and ST::resourceManager.
Member Function Documentation
void ST::CharacterState::enter () [virtual]
Enter Called when entering the state
Implements ST::GameState.
Definition at line 210 of file characterstate.cpp.
References createCreationWindow(), createSelectionWindow(), ST::graphicsEngine, ST::interfaceManager, mCreateWindow, mHalfScreenHeight, mHalfScreenWidth, and mSelectWindow.
void ST::CharacterState::exit () [virtual]
Exit Called when leaving the state
Implements ST::GameState.
Definition at line 232 of file characterstate.cpp.
References ST::interfaceManager, and mAvatar.
bool ST::CharacterState::update () [virtual]
Update Called every frame Return false to exit the game
Implements ST::GameState.
Definition at line 239 of file characterstate.cpp.
References ST::InputManager::getKey(), and ST::inputManager.
void ST::CharacterState::updateAvatar (BodyPart * body)
Used to update the character
Definition at line 415 of file characterstate.cpp.
References ST::Avatar::bodyparts, ST::graphicsEngine, mAvatar, and mCreateWindow.
Referenced by ST::change_part(), and ST::change_sex().
void ST::CharacterState::createSelectionWindow () [private]
Definition at line 252 of file characterstate.cpp.
References ST::del_character(), ST::Player::getCharacter(), ST::Character::getLevel(), ST::Being::getName(), ST::Player::getNumChars(), ST::graphicsEngine, ST::interfaceManager, mCreateWindow, mHalfScreenHeight, mHalfScreenWidth, mSelectWindow, ST::player, ST::radio_selected(), ST::select_character(), and ST::switch_char_window().
Referenced by enter().
void ST::CharacterState::createCreationWindow () [private]
Definition at line 318 of file characterstate.cpp.
References ST::Avatar::bodyparts, ST::change_part(), ST::change_sex(), createAvatar(), ST::ResourceManager::getBodyList(), ST::graphicsEngine, ST::interfaceManager, mAvatar, mCreateWindow, mHalfScreenHeight, mHalfScreenWidth, mSelectWindow, ST::resourceManager, ST::submit_new(), and ST::switch_char_window().
Referenced by enter().
void ST::CharacterState::createAvatar () [private]
Definition at line 391 of file characterstate.cpp.
References ST::Avatar::bodyparts, ST::ResourceManager::getDefaultBody(), ST::graphicsEngine, mAvatar, and ST::resourceManager.
Referenced by createCreationWindow().
Member Data Documentation
AG_Checkbox* ST::CharacterState::mSelected
Definition at line 99 of file characterstate.h.
Referenced by CharacterState().
std::vector<int> ST::CharacterState::mChosen
Definition at line 100 of file characterstate.h.
Referenced by ST::change_part(), ST::change_sex(), CharacterState(), and ST::submit_new().
int ST::CharacterState::mHalfScreenWidth [private]
Definition at line 103 of file characterstate.h.
Referenced by createCreationWindow(), createSelectionWindow(), and enter().
int ST::CharacterState::mHalfScreenHeight [private]
Definition at line 104 of file characterstate.h.
Referenced by createCreationWindow(), createSelectionWindow(), and enter().
AG_Window* ST::CharacterState::mSelectWindow [private]
Definition at line 105 of file characterstate.h.
Referenced by createCreationWindow(), createSelectionWindow(), and enter().
AG_Window* ST::CharacterState::mCreateWindow [private]
Definition at line 106 of file characterstate.h.
Referenced by createCreationWindow(), createSelectionWindow(), enter(), and updateAvatar().
Avatar* ST::CharacterState::mAvatar [private]
Definition at line 107 of file characterstate.h.
Referenced by CharacterState(), createAvatar(), createCreationWindow(), exit(), and updateAvatar().
The documentation for this class was generated from the following files:
programming/smalltowns/src/characterstate.h
programming/smalltowns/src/characterstate.cpp