Towns Life: ST::Map Class Reference
ST::Map Class Reference
#include <map.h>
Public Member Functions
Map ()
~Map ()
bool loadMap (const std::string &filename)
unsigned int getTileWidth ()
unsigned int getTileHeight ()
Private Member Functions
void addLayer (unsigned int width, unsigned int height, unsigned char *data, unsigned int len)
bool loadMapInfo (TiXmlElement *e)
bool loadTileset (TiXmlElement *e)
bool loadLayer (TiXmlElement *e)
Private Attributes
std::vector< Layer * > mLayers
std::vector< Tileset * > mTilesets
int mWidth
int mHeight
int mTileWidth
int mTileHeight
Detailed Description
The Map class contains the map data
Definition at line 108 of file map.h.
Constructor & Destructor Documentation
ST::Map::Map ()
Constructor
Definition at line 117 of file map.cpp.
References mHeight, mTileHeight, mTileWidth, and mWidth.
ST::Map::~Map ()
Definition at line 125 of file map.cpp.
Member Function Documentation
bool ST::Map::loadMap (const std::string & filename)
Load Map. Reads the map from a file
Parameters:
filename The name of the file to read the map from
Returns:
Returns true if successfully read in map
Definition at line 130 of file map.cpp.
References ST::ResourceManager::getDataPath(), loadLayer(), loadMapInfo(), loadTileset(), ST::logger, and ST::resourceManager.
unsigned int ST::Map::getTileWidth () [inline]
Returns width of tiles
Definition at line 128 of file map.h.
References mTileWidth.
unsigned int ST::Map::getTileHeight () [inline]
Returns height of tiles
Definition at line 133 of file map.h.
References mTileHeight.
void ST::Map::addLayer (unsigned int width, unsigned int height, unsigned char * data, unsigned int len) [private]
Add Layer. Adds a layer to the map
Definition at line 348 of file map.cpp.
References ST::graphicsEngine, mHeight, mLayers, mTileHeight, mTilesets, mTileWidth, mWidth, and ST::Layer::setTile().
Referenced by loadLayer().
bool ST::Map::loadMapInfo (TiXmlElement * e) [private]
Load Map Info from xml file. Gets the attributes from the XML element and stores them
Returns:
Returns whether it succeeded
Definition at line 193 of file map.cpp.
References ST::logger, mHeight, mTileHeight, mTileWidth, and mWidth.
Referenced by loadMap().
bool ST::Map::loadTileset (TiXmlElement * e) [private]
Load Tileset from xml file. Load in images for tileset
Returns:
Returns whether it succeeded
Definition at line 228 of file map.cpp.
References ST::ResourceManager::doesExist(), ST::ResourceManager::getDataPath(), ST::graphicsEngine, ST::Tileset::height, ST::Tileset::id, ST::logger, mTileHeight, mTilesets, mTileWidth, ST::resourceManager, ST::Tileset::tilename, and ST::Tileset::width.
Referenced by loadMap().
bool ST::Map::loadLayer (TiXmlElement * e) [private]
Load Layer from xml file. Load in data for layer
Returns:
Returns whether it succeeded
Definition at line 289 of file map.cpp.
References addLayer(), and ST::logger.
Referenced by loadMap().
Member Data Documentation
std::vector<Layer*> ST::Map::mLayers [private]
Definition at line 165 of file map.h.
Referenced by addLayer().
std::vector<Tileset*> ST::Map::mTilesets [private]
Definition at line 166 of file map.h.
Referenced by addLayer(), and loadTileset().
int ST::Map::mWidth [private]
Definition at line 167 of file map.h.
Referenced by addLayer(), loadMapInfo(), and Map().
int ST::Map::mHeight [private]
Definition at line 168 of file map.h.
Referenced by addLayer(), loadMapInfo(), and Map().
int ST::Map::mTileWidth [private]
Definition at line 169 of file map.h.
Referenced by addLayer(), getTileWidth(), loadMapInfo(), loadTileset(), and Map().
int ST::Map::mTileHeight [private]
Definition at line 170 of file map.h.
Referenced by addLayer(), getTileHeight(), loadMapInfo(), loadTileset(), and Map().
The documentation for this class was generated from the following files:
programming/smalltowns/src/map.h
programming/smalltowns/src/map.cpp